feat: add footer
DevKor-Team/DEVKOR-front pull request #8
Opened 2022-11-12 09:55 UTC by aiccuracy

- Footer 추가
- Footer에 있는 카카오/노션 등 아이콘 라우팅
- develop 에서 브랜치를 분기했어야 하는데 Feature/mypage에서 분기를 해서,, 지금 develop으로 바로 머지하는 것보다는 Feature/mypage로 머지한 후, myPage 작업 끝난 후 develop으로 일괄 머지하는게 나을 것 같습니다. (어차피 Footer 지금 당장 쓸 일 없으니) => commit diff 만 확인해주세요! (diff부분이 지금 딱 Footer 작업 사항들!)

[TODO 겸 논의사항]
- email의 경우, 클립보드 복사로 작업했는데, "클립보드에 복사되었습니다" 를 알림으로 띄워주어야 함 (어디다 어떻게 띄울지!)

2022-11-12 10:09 UTC, kunheekimkr requested changes
window.open("mailto:메일주소") 를 하게되면 바로 메일 보내는 창을 열수 있는데 클립보드에 복사 대신 이렇게 처리하는건 어떤가요??

window.open(`mailto:${DevKorApply.email}`);
로 이메일의 온클릭함수 바꿔보고 실행해봤는데 잘 되네요!
나머지는 문제 없는 것 같습니다~

2022-11-12 12:07 UTC, aiccuracy commented
> window.open("mailto:메일주소") 를 하게되면 바로 메일 보내는 창을 열수 있는데 클립보드에 복사 대신 이렇게 처리하는건 어떤가요??
> 
> `` window.open(`mailto:${DevKorApply.email}`); `` 로 이메일의 온클릭함수 바꿔보고 실행해봤는데 잘 되네요! 나머지는 문제 없는 것 같습니다~

해당 방식으로 하면 데스크톱 메일 앱에서 자동으로 열리는 것으로 알고 있는데, 제가 알기로는 메일 앱을 잘 쓰지 않는 것 같다는 생각이 들어서 이렇게 작업을 했었어요! 메일 앱을 쓰지 않는 사용자들에게 메일 앱을 열어준다면 UX 적으로 별로 좋지 않은 사용자 경험일 것 같은데 어떻게 생각하세용? 메일 앱을 얼마나 많은 사용자들이 쓰느냐가 판단의 핵심 기준이 될 것 같습니다!

2022-11-13 04:43 UTC, timosean approved these changes
저도 사실 mail앱을 쓰진 않아서 그걸 열어주는게 UX적으로 좋지 않다고 판단되긴 합니당..!
대신에 페이지 가장 우상단에 "클립보드에 복사되었습니다" 를 띄우는 것이 어떨까요?
아니면 코랩처럼 좌하단에?

2022-11-13 11:36 UTC, kunheekimkr commented
앗 그렇다면 그냥 클립보드로 복사하고 알림 띄우는게 더 좋을 것 같네요!
클릭하는 버튼이 화면의 하단에 있으니까 알림도 하단 중앙에 띄우는 게 보기 편할 것 같습니다.

2022-11-13 11:47 UTC, kunheekimkr approved these changes

2022-11-17 04:33 UTC, timosean approved these changes
LGTM*1000000000000

2022-11-17 04:33 UTC, timosean commented on components/Footer.tsx
>  import { DevKorApply } from "../constants/devkor";
오 DevkorApply 따로 만들어서 router.push 해준거 너무 깔끔하고 보기 좋아요 bb

2022-11-17 04:33 UTC, timosean commented on components/Footer.tsx
> +                <Alert />
`setCopied`가 여기에서 사용되었군용!_! 역시... 너무 좋아요 코드

2023-01-01 10:31 UTC, merged